using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace TestConsole.UnitTestable
{
    /// <summary>
    /// Since we cannot directly reference a shared project from a unit test project,
    /// we reference the TestConsole project instead, which implements the desired tests.
    /// </summary>
    public static class Misc
    {
        public static void CheckApiFormat()
        {
            // TODO: unit test checking the same request both in xml and json, and comparing them.
            // IIRC the json generated by last.fm is worse than xml
            // (ie: one xml element is one json property, several xml elements become a json array (!))
        }
    }
}
